Repository cbg-ethz/PYggdrasil, pull requests merged in 2023-07, with the labels that each got.

#105 Add more badges to ReadMe
  README.md
Labels: ❗priority: low, ⏰ time estimate: S

#106 Setting up the HPC Environment
  README.md
  environment.yml
  workflows/README.md
  workflows/Snakefile
  workflows/analyze.smk
  workflows/mark00.smk
  workflows/mark01.smk
  workflows/tree_inference.smk
  workflows/visualize.smk
Labels: 🕮 action: documentation, 🦾 action: enhancement, ❗priority: high, 🧩 in sprint, ⏰ time estimate: M

#103 Reinstating scphylo Ancestor-Descendant Metric
  src/pyggdrasil/analyze/_metrics.py
  src/pyggdrasil/distances/__init__.py
  src/pyggdrasil/distances/_scphylo_wrapper.py
  src/pyggdrasil/distances/_similarities.py
  tests/distances/test_scphylo_wrapper.py
  workflows/mark01.smk
Labels: 🐛 bug, ❗priority: medium, 🧩 in sprint, ⏰ time estimate: S

#109 Enforce Unique Star Tree Filenames
  src/pyggdrasil/tree_inference/_file_id.py
  workflows/mark01.smk
Labels: 🐛 bug, 🦾 action: enhancement, ❗priority: high, ⏰ time estimate: S

#104 Implementation of MARK02 Convergence
  src/pyggdrasil/tree_inference/__init__.py
  src/pyggdrasil/tree_inference/_config.py
  workflows/Snakefile
  workflows/mark01.smk
  workflows/mark01_dag.pdf
  workflows/mark02.smk
Labels: 🦾 action: enhancement, ❗priority: high, 🧩 in sprint, ⏰ time estimate: M

#111 Revising MARK02
  src/pyggdrasil/analyze/_metrics.py
Labels: 🐛 bug, ❗priority: high, ⏰ time estimate: S

#112 Revision MARK01
  scripts/make_huntress.py
Labels: ❗priority: low, ⏰ time estimate: S, 🧪 action: experiment

#115 Add snakefmt
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  pyproject.toml
  workflows/Snakefile
  workflows/analyze.smk
  workflows/tree_inference.smk
  workflows/visualize.smk
Labels: 🦾 action: enhancement, ❗priority: low, ⏰ time estimate: S

#114 Implementing MARK03 Experiment
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  pyproject.toml
  scripts/make_huntress.py
  scripts/run_mcmc.py
  src/pyggdrasil/tree_inference/__init__.py
  src/pyggdrasil/tree_inference/_file_id.py
  src/pyggdrasil/tree_inference/_interface.py
  src/pyggdrasil/tree_inference/_mcmc.py
  src/pyggdrasil/tree_inference/_mcmc_sampler.py
  src/pyggdrasil/tree_inference/_mcmc_util.py
  src/pyggdrasil/tree_inference/_simulate.py
  src/pyggdrasil/tree_inference/_tree.py
  src/pyggdrasil/tree_inference/_tree_generator.py
  src/pyggdrasil/tree_inference/_tree_mcmc.py
  tests/tree_inference/test_file_id.py
  tests/tree_inference/test_mcmc.py
  tests/tree_inference/test_tree.py
  workflows/README.md
  workflows/Snakefile
  workflows/analyze.smk
  workflows/mark01.smk
  workflows/mark02.smk
  workflows/mark03.smk
  workflows/tree_inference.smk
Labels: 🦾 action: enhancement, ❗priority: high, 🧩 in sprint, ⏰ time estimate: L, 🧪 action: experiment

#118 Adding Report Visualisations Workflow
  src/pyggdrasil/__init__.py
  src/pyggdrasil/visualize/_tree.py
  workflows/Snakefile
  workflows/mark_viz.smk
  workflows/visualize.smk
Labels: 🦾 action: enhancement, ❗priority: low, ⏰ time estimate: S

#117 Experimental Run: Mark01
  scripts/cell_simulation.py
  scripts/make_huntress.py
  src/pyggdrasil/distances/_scphylo_wrapper.py
  src/pyggdrasil/tree_inference/_simulate.py
  workflows/mark01.smk
  workflows/tree_inference.smk
Labels: 🧪 action: experiment

#124 Fix Analyze Analyze Metric Bug
  workflows/analyze.smk
Labels: 🐛 bug, ❗priority: high, ⏰ time estimate: S

#125 Fixing Mark03 rule error
  workflows/analyze.smk
  workflows/mark02.smk
  workflows/mark03.smk
  workflows/mark_viz.smk
  workflows/tree_inference.smk
  workflows/visualize.smk
Labels: 🐛 bug, ❗priority: medium, ⏰ time estimate: S

#128 Update scphylo / fix HUNTRESS implementation
  pyproject.toml
Labels: 🐛 bug

#129 Revision of MARK03 plots
  workflows/mark03.smk
Labels: 🐛 bug

#131 Revising Mark01: AD Bug + Ploting
  src/pyggdrasil/distances/_scphylo_wrapper.py
  workflows/mark01.smk
  workflows/tree_inference.smk
Labels: 🐛 bug, ❗priority: medium, ⏰ time estimate: S

#134 Initial Experiments Output Description
  workflows/mark01.smk
  workflows/mark02.smk
  workflows/mark03.smk
Labels: 🕮 action: documentation, ⏰ time estimate: S
